export const START_LOADING = "START_LOADING";

export const GET_LEADS_DATA_SUCCESS = "GET_LEADS_DATA_SUCCESS";
export const ADD_NEW_LEAD = "ADD_NEW_LEAD";
export const UPDATE_COMMUNICATION_DATA = "UPDATE_COMMUNICATION_DATA";
export const DELETE_LEAD = "DELETE_LEAD"; 

export const STOP_LOADING = "STOP_LOADING";
